### ISSUE TITLE
Day graph doesn't show the "last 24 hours"

### ISSUE THREAD

**Issue by woll** [nophead/EnviroPlusWeb#2]
When I show the "day" graph, it doesn't seem to show the "last 24 hours", but only the data since the previous midnight. The graph is 'flat' for the hours before the last midnight. In the attached screenshot, it's just after midnight. The graph is almost completely flat except at the far righthand side, where the live data is being updated. This behaviour doesn't seem to be shown on the screenshots that other people have posted of EnviroPlusWeb. Any ideas anyone?
![Screen Shot 2020-01-12 at 15 15 02](https://user-images.githubusercontent.com/2272798/72221076-10470600-354f-11ea-9d27-3cb4adf3911a.jpg)

**Comment by woll** [comment]
Also my "week" graph seems to have similar 'flat' areas in it.
![Screen Shot 2020-01-12 at 15 21 45](https://user-images.githubusercontent.com/2272798/72221109-4edcc080-354f-11ea-8cf2-5859943f06ec.jpg)

**Comment by nophead** [comment]
My day view definitely shows 24 hours. Did you have it running yesterday?

![image](https://user-images.githubusercontent.com/566149/72221919-f4dff900-3556-11ea-9a8c-f7bc4d5f9e6f.png)


If there is missing data in the files it will pad them out with flat areas like that.  Did you have it running constantly for a week?

I don't know what all the white areas are.

**Comment by nophead** [comment]
Which time zone are you in? I wonder if there is a bug when not using GMT.

**Comment by woll** [comment]
Sorry, I should have explained that I've edited the html templates to change the appearance of the graphs. I've disabled the drawing of all the pm values except pm2.5 and pm10, and 'filled' the graph for those 2 pm values rather than just drawing a line. I'm pretty sure that none of the changes I've made would create those 'flat' areas in the graph, but I should probably go back to running the code exactly as from GitHub to be sure.

It's been running continuously for over a week.
The sensor is in Japan, so maybe there IS some kind of timezone problem. 
From your description of how it works, it certainly looks as if there is 'missing data'. I'll try and take a closer look.

**Comment by woll** [comment]
It looks as if the 'data' files do contain all the samples for the whole day, although the first record is actually from the day before. Is that maybe causing the problem?
```
data/2020_012
{"time": "Sat Jan 11 23:59:54 2020", "temp": 12.7, "humi": 36.8, "pres": 1009.7, "lux": 0.0, "oxi": 80.7, "red": 288.7, "nh3": 194.7, "pm03": 971.5, "pm05": 304.8, "pm10": 73.3, "pm25": 10.7, "pm50": 0.3, "pm100": 11.4}
{"time": "Sun Jan 12 00:04:53 2020", "temp": 12.8, "humi": 36.5, "pres": 1009.7, "lux": 0.0, "oxi": 83.4, "red": 289.2, "nh3": 196.9, "pm03": 911.9, "pm05": 288.3, "pm10": 69.0, "pm25": 10.4, "pm50": 0.3, "pm100": 10.9}
{"time": "Sun Jan 12 00:09:53 2020", "temp": 12.7, "humi": 36.7, "pres": 1009.6, "lux": 0.0, "oxi": 85.7, "red": 291.7, "nh3": 198.7, "pm03": 926.1, "pm05": 285.1, "pm10": 70.8, "pm25": 10.7, "pm50": 0.5, "pm100": 12.0}
{"time": "Sun Jan 12 00:14:54 2020", "temp": 12.7, "humi": 36.7, "pres": 1009.6, "lux": 0.0, "oxi": 86.6, "red": 294.8, "nh3": 201.4, "pm03": 903.4, "pm05": 283.6, "pm10": 70.2, "pm25": 10.3, "pm50": 0.4, "pm100": 10.8}
.
.
.
{"time": "Sun Jan 12 23:49:54 2020", "temp": 7.4, "humi": 36.8, "pres": 1012.5, "lux": 0.0, "oxi": 3575.1, "red": 516.0, "nh3": 1185.1, "pm03": 1179.3, "pm05": 378.9, "pm10": 68.0, "pm25": 12.0, "pm50": 0.2, "pm100": 13.3}
{"time": "Sun Jan 12 23:54:54 2020", "temp": 7.4, "humi": 36.5, "pres": 1012.5, "lux": 0.0, "oxi": 3560.0, "red": 514.6, "nh3": 1195.1, "pm03": 1268.8, "pm05": 403.6, "pm10": 72.8, "pm25": 13.0, "pm50": 0.6, "pm100": 14.2}
```

**Comment by nophead** [comment]
That is not what my files look like:
```
{"time": "Wed Sep 11 00:00:00 2019", "temp": 23.4, "humi": 53.6, "pres": 1013.1, "lux": 35.0, "oxi": 48.0, "red": 475.0, "nh3": 251.8, "pm03": 11035.9, "pm05": 3638.7, "pm10": 989.5, "pm25": 107.6, "pm50": 15.6, "pm100": 14.9}
{"time": "Wed Sep 11 00:05:00 2019", "temp": 23.4, "humi": 53.6, "pres": 1013.1, "lux": 35.1, "oxi": 48.0, "red": 474.8, "nh3": 251.9, "pm03": 10932.8, "pm05": 3595.9, "pm10": 975.3, "pm25": 109.8, "pm50": 14.0, "pm100": 10.5}
{"time": "Wed Sep 11 00:10:00 2019", "temp": 23.5, "humi": 53.4, "pres": 1013.0, "lux": 14.4, "oxi": 48.0, "red": 474.7, "nh3": 251.5, "pm03": 10819.2, "pm05": 3572.3, "pm10": 954.3, "pm25": 113.9, "pm50": 13.8, "pm100": 14.3}
...
{"time": "Wed Sep 11 23:40:00 2019", "temp": 23.5, "humi": 55.8, "pres": 1017.9, "lux": 7.4, "oxi": 53.8, "red": 427.5, "nh3": 237.2, "pm03": 1461.0, "pm05": 470.4, "pm10": 132.3, "pm25": 12.9, "pm50": 2.2, "pm100": 2.5}
{"time": "Wed Sep 11 23:50:00 2019", "temp": 23.5, "humi": 55.7, "pres": 1018.1, "lux": 7.5, "oxi": 48.0, "red": 478.5, "nh3": 222.7, "pm03": 1248.6, "pm05": 414.7, "pm10": 106.8, "pm25": 12.1, "pm50": 1.1, "pm100": 1.3}
{"time": "Wed Sep 11 23:55:00 2019", "temp": 23.5, "humi": 55.7, "pres": 1018.1, "lux": 10.0, "oxi": 50.6, "red": 466.7, "nh3": 236.1, "pm03": 1231.7, "pm05": 407.3, "pm10": 105.2, "pm25": 9.5, "pm50": 1.4, "pm100": 2.1}
```

The times should be on 5 minute boundaries.

**Comment by woll** [comment]
Hmm, I guess my changes to the style of the graph must have broken it somehow! I've just gone back to the code previously downloaded from GitHub and the times are now at the 5 minute boundaries. I'll close this issue - sorry for the spurious report!

**Comment by nophead** [comment]
I can't see how the display of the graph would affect the data collection and file writing. The line that ensures the readings are on 5 minute boundaries is this one: https://github.com/nophead/EnviroPlusWeb/blob/master/app.py#L211
