### ISSUE TITLE
Non ascii code error

### ISSUE THREAD

**Issue by Hagoort** [nophead/EnviroPlusWeb#3]
I had to put this "# -*- coding: utf-8 -*-", the star signs between the -- disappear in this issue field, as the first line in app.py to get it working and of course use " sudo ./install-service.sh". Sorry I'm new to Github. I don't know if this is the right place for reactions. Thanks for your work.

**Comment by nophead** [comment]
Interesting. Probably because I pasted a degree symbol into the file. I don't know why it worked for me though. What locale do you use?

**Comment by zpydr** [comment]
@nophead 
+1
Adding
# -- coding: utf-8 --
to the top of the app.py file resolves this issue.
Thank you for this nice interface!

**Comment by nophead** [comment]
Are you using Python 2.x? Python3.x should not need it.

**Comment by zpydr** [comment]
Yes, this is due to using python2. Forked this:
https://github.com/zpydr/EnviroPlusWeb

Thanks again!

**Comment by nophead** [comment]
Python2 is obsolete since January.

**Comment by nophead** [comment]
I added one anyway.
