### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by goodald** [nophead/EnviroPlusWeb#4]
line 77. path = os.path.dirname(os.path.realpath(__file__)) + "/../enviroplus-python/examples/fonts"

fonts no longer exists so you get the following error Traceback (most recent call last):
File "app.py", line 77, in <module>
smallfont = ImageFont.truetype(path + "/Asap/Asap-Bold.ttf", 10)
File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 280, in truetype
return FreeTypeFont(font, size, index, encoding, layout_engine)
File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 145, in __init__
layout_engine=layout_engine)
OSError: cannot open resource

bensimmo on the raspberrypi.org forum has kindly suggested a fix which involves the following:

sudo pip3 install fonts
sudo pip3 install font-roboto

then adding to the app.py

from fonts.ttf import RobotoMedium as UserFont

removing  - smallfont = ImageFont.truetype(path + "/Asap/Asap-Bold.ttf", 10)

and replacing it with 

smallfont = ImageFont.truetype(UserFont, 10)

I've also comment out line 75

**Comment by n6egy** [comment]
I also am having trouble with this font issue, as follows:

>>> %Run app.py
Traceback (most recent call last):
  File "/home/pi/EnviroPlusWeb/app.py", line 78, in <module>
    smallfont = ImageFont.truetype(path + "/Asap/Asap-Bold.ttf", 10)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/lib/python3/dist-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
OSError: cannot open resource
>>> 
Chris, would you take a minute (maybe more) to help me out.  I tried installing Roboto Medium font in my  /home/pi folder as noted above.  No joy. 
Thanks in advance for helping.
John

**Comment by nophead** [comment]
If you want to use Roboto Medium you also have to make the changes to the code that @goodald showed above. Your error message says it is still looking for Asap-Bold.

**Comment by n6egy** [comment]
I wasn't clear.  I tried following @goodald's suggestions several times and still had error messages.
How do I alter your code to find Asap-Bold using the latest version of Raspbian and an RPi4?
John

**Comment by nophead** [comment]
The Asap font was part of the pimoroni library but they seem to have removed it. You could get it from an older versio. E.g. https://github.com/pimoroni/enviroplus-python/tree/391bec805e2503f517fbec5d864f4d353e5f00ab/examples/fonts/Asap

Or you can do what @goodald suggests. Install the alternative font
```
sudo pip3 install fonts
sudo pip3 install font-roboto

````

And then change app.py to use that instead.

Add this near the start
```
from fonts.ttf import RobotoMedium as UserFont
```

And then change the line 
```
smallfont = ImageFont.truetype(path + "/Asap/Asap-Bold.ttf", 10)
```

to 

```
smallfont = ImageFont.truetype(UserFont, 10)
```

**Comment by n6egy** [comment]
Have made the changes  above and get the following response:

>>
*Serving Flask app "app" (lazy loading)
*Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 *Debug mode: off
[Errno 13] Permission denied
Waiting for background to quit
>>

The path to the new font is:
/usr/share/fonts/truetype/roboto

Line 23 in the code is:  23  `from fonts.ttf import RobotoMedium as UserFont
`
Line 82 in the code is:  82   `smallfont = ImageFont.truetype(UserFont, 10)`

Here's the modified app in  text form for reference:

[app.txt](https://github.com/nophead/EnviroPlusWeb/files/4534210/app.txt)

Have Googled Errno 13 and tried to correct the error to no avail.  
Please give me a hand.

**Comment by nophead** [comment]
Are you running it with sudo python3? It has to be route to serve web pages on port 80.

**Comment by n6egy** [comment]
I wasn’t.  Does everyone in the RPi-Linux-Python world know that except me?
It does work now.

Thanks,

John

**Comment by nophead** [comment]
Probably not. It is normally run as a service with ```install-service.sh```.

**Comment by n6egy** [comment]
So I should run the install.sh script?

**Comment by nophead** [comment]
Yes it makes a service that starts in the background whenever the RPI boots. Run it with sudo.

**Comment by jpvalery** [comment]
I made those changes in my fork. Would you like me to open a PR to fix this issue?

**Comment by nophead** [comment]
Yes please.
