### ISSUE TITLE
Web service not starting

### ISSUE THREAD

**Issue by n0sn3b** [nophead/EnviroPlusWeb#6]
Hey there,
I'm new to flask, just installed it to try out your app.
First thing first, thank you for sharing your work!

Since i'm new to flask i started with a "hello world". It's working. I used this tutorial: 
https://flask.palletsprojects.com/en/1.1.x/quickstart/
Basically copied the hello world there, started it with 
```
root@local# export FLASK_APP=hello.py
root@local# python3 -m flask run
```

The browser shows hello world, all good.

then for your app:
```
root@local# export FLASK_APP=app.py
root@local# python3 -m flask run
```

here's the output:
```
* Serving Flask app "app.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Particle read failed: SerialTimeoutError
```

But no web service is running. Nothing on port 80. I can't find any error.
`root@local#lsof -i TCP` doesn't show python binding to any port

Any idea what's happening?

**Comment by nophead** [comment]
Looks like the the particle sensor is not working. Do you have one, is it plugged in?

I run with sudo to take over port 80 but I haven't used the -m flask option. I just use:
```
sudo python3 app.py
```

**Comment by n0sn3b** [comment]
I do not have a particle sensor, but i  figured it was failing gracefully for that one? Just outputting the error message?
Starting it with `sudo python3 app.py` does not change anything:
`user@local$ sudo python3 app.py
Particle read failed: SerialTimeoutError
Particle read failed: SerialTimeoutError
Particle read failed: SerialTimeoutError
Particle read failed: SerialTimeoutError`

still no port binded by python, confirmed via lsof.

**Comment by nophead** [comment]
It won't work without a particle sensor unless you comment out all the code that uses it. It loops forever trying to get a response, so will never get as far as running the flask app.

**Comment by n0sn3b** [comment]
That's right, it works. I don't know Python but i can try to use this as a way to learn.
I'll work on putting some if statements to allow selection of particle sensor availability

**Comment by e-m-m-a** [comment]
Hello, In Magpie you mention commenting out lines of the code to get this to work without the particle sensor. I have tried this multiple times and just get a variety of indent and other errors. Any chance you could upload this version of the code?

**Comment by e-m-m-a** [comment]
You also mention Yes you could hack out the reading of it from app.py.

If you are not planning to get one remove the entries from the record and also remove the display here: https://github.com/nophead/EnviroPlusWeb/blob/master/templates/readings.html#L10 4 and the graphing here: https://github.com/nophead/EnviroPlusWeb/blob/master/templates/index.html#L77 5.

If you are planning to get one in the future then write zeros to the record and keep the display stuff in place.

I have one on order - how do I write zero's to the record??

**Comment by nophead** [comment]
Sorry but I haven't written anything in Magpie. I only realised somebody had written about this program when it was pointed out to me as I don't read it either.

To work properly without the sensor but also work when one is added needs quite a lot of changes as the LCD screen format and the web page format and graphs need to change. Simply writing zeros is easy but it will also display zeros. Fine if you are getting a sensor soon but not very good for people that don't intend to get one.

I will add a change to write zeros for time being.

**Comment by n0sn3b** [comment]
I made a patch to make it work without the particule sensor, with if statements and an entry in the config file. I sent the merge request.

**Comment by nophead** [comment]
Yes but that doesn't write zeros, so I think it would not allow a particle sensor to be added later.

**Comment by n0sn3b** [comment]
i see

**Comment by nophead** [comment]
@e-m-m-a, changing [line 20](https://github.com/nophead/EnviroPlusWeb/blob/master/app.py#L20) to `particle_sensor = False` should make it run without a particle sensor now.

**Comment by e-m-m-a** [comment]
That is fantastic and working now, thank you very much

**Comment by nophead** [comment]
I pushed a further update that makes the display and  graph adapt to showing the particles or not.
