### ISSUE TITLE
Option for no gasses ?

### ISSUE THREAD

**Issue by Trotter73** [nophead/EnviroPlusWeb#8]
Hi,

Would there be any chance of an option or a version for the Enviro version of the HAT, the one without the gasses sensor ?

I've had a play at commenting stuff out, however have to say this is a bit beyond me.

Regards,
Me

**Comment by nophead** [comment]
Is the rest of the Enviro board the same? I.e. all the other devices on the board at the same addresses?

**Comment by nophead** [comment]
Is it possible to add the particle sensor to the Enviro board? If so that would be four versions to support.

**Comment by Trotter73** [comment]
> Is the rest of the Enviro board the same? I.e. all the other devices on the board at the same addresses?

Hi,

Thanks for getting back so quickly, appreciated, having a quick read and play the addresses of the common sensors are the same between the two versions, no differences, the non-gasses version does not have the connector for the particulate sensor so that cannot be added to the board...

Regards,
Ne.

**Comment by nophead** [comment]
OK I will look at adding another option then.

**Comment by Trotter73** [comment]
Really appreciated!!

**Comment by nophead** [comment]
OK, I added an option for no gas sensor with this commit: https://github.com/nophead/EnviroPlusWeb/commit/b61341983fa6721c10fb6accd886a2184a86ab0d. If you set 
```
particle_sensor = False
gas_sensor = False
```

It will just leave temperature, humidity, pressure and lux. The display format could be improved by switching to 1 column and a larger font.

**Comment by Trotter73** [comment]
Hi,

 Just cloned it and taken it for a spin, perfect, a huge thanks, really appreciated ! 

 Would the fan code still be relevant without the measurement of particulates or gasses ? Just a thought....

**Comment by nophead** [comment]
The fan is just to keep the PCB cool to try and get temperature and humidity correct. The problem is it is too noisy, so mine are relegated to a shed and a garage.

**Comment by Trotter73** [comment]
OK cool, thanks again for the no gas option, appreciated !
